version: '3.3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ${APP_NAME}/web
    environment:
      - TZ=Asia/Tokyo
    container_name: ${APP_NAME}_web
    tty: true
    volumes:
      - ../src:/var/www
    working_dir: /var/www/${APP_NAME}
    ports:
      - 80:80
      # - 8000:8000

  db:
    container_name: ${APP_NAME}_postgres
    image: postgres:12.3
    #build:
      #context: ./docker/mysql
      #dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      # 設定ファイル
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      # データベースのデータ
      - ./postgres/data:/var/lib/postgresql/data
      - ../sql:/root
    ports:
      - 15432:5432
